version: '3'

services:
  payments-ms:
    build: ./
    ports:
      - 3004:3004
    volumes:
      - ./src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3004
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET=${STRIPE_SECRET}
      - ENDPOINT_SECRET=${ENDPOINT_SECRET}
      - URL_SUCCESS=${URL_SUCCESS}
      - URL_CANCEL=${URL_CANCEL}
    networks:
      - app_network

networks:
  app_network:
    external: true
